# Generated by Django 3.0.4 on 2020-04-03 21:45

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gamblr_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', jsonfield.fields.JSONField()),
            ],
        ),
    ]
